# Generated by Django 3.0.5 on 2020-04-19 08:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 17, 4, 189866, tzinfo=utc))),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 17, 4, 189866, tzinfo=utc))),
                ('status', models.IntegerField(default=0)),
                ('place_name', models.TextField()),
                ('place_country', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.CountryGroup')),
                ('place_group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.PlaceGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.TextField()),
                ('created_at', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 17, 4, 189866, tzinfo=utc))),
                ('updated_by', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(default=datetime.datetime(2020, 4, 19, 8, 17, 4, 189866, tzinfo=utc))),
                ('status', models.IntegerField(default=0)),
                ('item_code', models.CharField(max_length=512, unique=True)),
                ('maker', models.TextField(blank=True, null=True)),
                ('item_name', models.TextField()),
                ('item_spec', models.TextField()),
                ('image', models.ImageField(blank=True, upload_to='%Y/%m/%d')),
                ('item_group1', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.ItemGroup1')),
                ('item_group2', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='settings.ItemGroup2')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.UnitGroup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
